name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
    build:
    env: 
      platform: aws
      region: us-east-1
      account: 0123456789012

      
    runs-on: ubuntu-latest
  
    steps: 
      - name: "Mostrar Mensaje"
        run: echo "Hola Mundo"
        
      - name: 
        run:
          echo"esto es el valor de platform: ${{ platform }}"
          echo"esto es el valor de region: ${{ region }}"
          echo"esto es el valor de account: ${{ account }}"  
